### PR TITLE
scripts/build.sh: bump version to 1.0.0-beta.6

### PR DESCRIPTION
**Pull request by unclejack**

### CODE REVIEW

**Comment by dseevr** [comment]
We should extract the version string defaults into a variable at the top so it doesn't need to be edited in multiple places for every release

**Comment by neelimamukiri** [comment]
@dseevr, technically we can change only one of these components. If we have to add a hotfix to auth_proxy, there is no need to rev up netplugin etc.

**Comment by dseevr** [comment]
@neelimamukiri good point, we can't assume lockstep on all components 😄

**Comment by unclejack** [comment]
Can we merge this PR?

**Comment by dseevr** [comment]
Your wish is my command

**Pull request merged**
